apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventhub.fullname" . }}-config
  labels:
    {{ include "eventhub.labels" .  | nindent 4 }}
data:
  eventhub.conf: {{ toYaml .Values.config  | nindent 3 }}
