{{- with .Values.jwtSecret }}
 {{- if and .value (not (and .existingSecret .existingSecret.name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventhub.jwtSecretName" $ }}
  labels:
    {{ include "eventhub.labels" $  | nindent 4 }}
type: Opaque
data:
  jwt_secret: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}
