{{- if .Values.https.enabled }}
{{- $tls := .Values.https.tls | default dict }}
{{- if and (not $tls.existingSecret) $tls.cert $tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventhub.tlsSecretName" . }}
  labels:
    {{ include "eventhub.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.cert | b64enc | quote }}
  tls.key: {{ $tls.key | b64enc | quote }}
{{- end }}
{{- end }}
